services:
  pgdatabase:
    image: postgres:15
    networks:
      - omopnet
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: oma-opiskelijavalinta
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    user: "${USERID}:${GROUPID}"
    env_file: 
     - .env.docker
     - path: .env.docker.local
       required: false
    environment:
      USER: appuser
      HOME: /home/appuser
      MAVEN_CONFIG: /home/appuser/.m2
      # Ei käynnistetä tietokantaa automaattisesti backendin kanssa DevApp:ssa
      NO_DB: true
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app
      SPRING_DATASOURCE_URL: jdbc:postgresql://pgdatabase:5432/oma-opiskelijavalinta
      MAVEN_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - "8555:8555"
      - "5055:5055"
    networks:
      - omopnet
    volumes:
      - .:/app
      - ~/.m2:/home/appuser/.m2
    depends_on:
      - pgdatabase
  nginx:
    image: nginx:alpine
    env_file:
      - .env.docker
      - path: .env.docker.local
        required: false
    ports:
      - "80:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/templates/default.conf.template:ro
    networks:
      - omopnet
    depends_on:
      - backend
networks:
  omopnet:
    driver: bridge
volumes:
  pgdata:
