name: setup-node-env
description: 'Setup Node.js environment'
inputs:
  project_path:
    description: Path to the pnpm-lock.yaml
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
    - name: Enable corepack
      shell: bash
      run: corepack enable
    - name: Configure pnpm dependencies cache
      uses: actions/setup-node@v6
      with:
        cache: 'pnpm'
        cache-dependency-path: ${{ inputs.project_path }}/pnpm-lock.yaml
        registry-url: 'https://npm.pkg.github.com'
        scope: '@opetushallitus'
    - name: Install pnpm dependencies
      if: steps.node_modules-cache.outputs.cache-hit != 'true'
      shell: bash
      run: cd ${{inputs.project_path}} && pnpm i --prefer-offline
