CREATE UNLOGGED TABLE IF NOT EXISTS PAATETTAVAT_OPISKELUOIKEUDET (
    ID SERIAL PRIMARY KEY,
    SESSION_ID CHAR(36) NOT NULL,
    HAKUKOHDE_OID VARCHAR(50) NOT NULL,
    PAATETTAVAT_OIKEUDET JSON NOT NULL,
    CONSTRAINT SESSION_MAPPING_FK FOREIGN KEY (SESSION_ID) REFERENCES SPRING_SESSION(SESSION_ID) ON DELETE CASCADE
);
