CREATE UNLOGGED TABLE IF NOT EXISTS CAS_SESSION_MAPPING (
    MAPPED_TICKET_ID VARCHAR PRIMARY KEY,
    SESSION_ID CHAR(36) NOT NULL UNIQUE,
    CONSTRAINT SESSION_MAPPING_FK FOREIGN KEY (SESSION_ID) REFERENCES SPRING_SESSION(SESSION_ID) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS CAS_SESSION_MAPPING_IX1 ON CAS_SESSION_MAPPING (MAPPED_TICKET_ID);