export enum Valintatila {
  HYVAKSYTTY = 'HYVAKSYTTY',
  HARKINNANVARAISESTI_HYVAKSYTTY = 'HARKINNANVARAISESTI_HYVAKSYTTY',
  VARASIJALTA_HYVAKSYTTY = 'VARASIJALTA_HYVAKSYTTY',
  VARALLA = 'VARALLA',
  PERUUTETTU = 'PERUUTETTU',
  PERUNUT = 'PERUNUT',
  PERUUNTUNUT = 'PERUUNTUNUT',
  HYLATTY = 'HYLATTY',
  KESKEN = 'KESKEN',
}
